#!/usr/bin/perl

#----------------------------------------------------------------------
# copyright (C) 2016 Koozali SME Server
#		
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
#----------------------------------------------------------------------
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open_ro()  or die 'cannot open the database';
my $SystemName = $db->get_value('SystemName');
my $DomainName = $db->get_value('DomainName');

#set the command
my $command = "exec /bin/hostnamectl set-hostname $SystemName.$DomainName";

open EXEC, "$command |" or die "cannot set hostname: $!";
close EXEC;
