#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2005 Mitel Networks Corporation
# copyright (C) 2024 Koozali foundation inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::AccountsDB;
use esmith::util;
use utf8;
use esmith::util::ldap;

my $conf = esmith::ConfigDB->open_ro;
my $accounts = esmith::AccountsDB->open;

my $ldapauth = $conf->get('ldap')->prop('Authentication') || 'disabled';
my $x = 0; # exit value

# prepare LDAP bind
my $ldap=esmith::util::ldap->new();

my $event = $ARGV [0];
my $userName = $ARGV [1];

#------------------------------------------------------------
# Create the Unix account
#------------------------------------------------------------

die "username argument missing" unless defined ($userName);

my $acct = $accounts->get($userName);
unless (defined $acct and $acct->prop('type') eq "user")
{
    die "Account $userName is not a user account; create user failed.\n";
}

my $lock = undef;
my $uid;
unless ($uid = $acct->prop('Uid'))
{
    use esmith::lockfile;

    $lock = esmith::lockfile::LockFileOrWait("/home/e-smith/db/accounts");
    $uid = $accounts->get_next_uid;
    $acct->set_prop('Uid', $uid);
}
my $gid = $acct->prop('Gid') || $uid;
my $first = stringToASCII($acct->prop('FirstName')) || '';
my $last = stringToASCII($acct->prop('LastName')) || '';
my $phone = stringToASCII($acct->prop('Phone')) || '';
my $company = stringToASCII($acct->prop('Company')) || '';
my $dept = stringToASCII($acct->prop('Dept')) || '';
my $city = stringToASCII($acct->prop('City')) || '';
my $street = stringToASCII($acct->prop('Street')) || '';
my $shell = $acct->prop('Shell') || '/usr/bin/false';
my $groups = "shared";

if ($ldapauth ne 'enabled')
{
    # Create the user's unique group first
    system(
            "/usr/sbin/groupadd",
            "-g",
            $gid,
            $userName
        ) == 0 or ( $x = 255, warn "Failed to create (unix) group $userName.\n" );

    # Now create the user account
    system(
            "/usr/sbin/useradd",
            "-u", $uid,
            "-g", $gid,
            "-c", "$first $last",
            "-d", "/home/e-smith/files/users/$userName",
            "-G", "$groups",
            "-m",
            "-k", "/etc/e-smith/skel/user",
            "-s", "$shell",
            $userName
        ) == 0 or ( $x = 255, warn "Failed to create (unix) account $userName.\n" );
}

# Create the user's unique group first (in ldap)
my $result = $ldap->ldapgroup($acct);
$result && ( $x = $ldapauth ne 'enabled' ? $x : 255, warn "Failed to create (ldap) group $userName.\n" );

# Now create the user account (in ldap)
$result = $ldap->ldapuser($acct);
$result && ( $x = $ldapauth ne 'enabled' ? $x : 255, warn "Failed to create (ldap) account $userName.\n" );

# add to supplementary group
my @UserArr = ($userName);
$result = $ldap->ldapsetgroupmembers($userName,\@UserArr);
$result &&  ( $result != 20 ) && ( $x = $ldapauth ne 'enabled' ? $x : 255, warn "Failed to add (ldap) account $userName to supplementary group.\n" );

# Release lock if we have one
$lock && esmith::lockfile::UnlockFile($lock);

# Set initial permissions on user's root directory.

chmod 0700, "/home/e-smith/files/users/$userName";

# lock user password
if ($ldapauth ne 'enabled')
{
    system("/usr/bin/passwd", "-l", "$userName")
        and ( $x = 255, warn "Could not lock (unix) password for $userName\n" );
}

# esmith::util::ldap already lock user on creation, this avoid one more ldap write access.

system("/usr/bin/smbpasswd", "-a", "-d", "$userName")
    and ( $x = 255, warn "Could not lock (smb) password for $userName\n" );

my $serv = $conf->get('samba') ;
if ((defined $serv) && ($userName ne 'administrator'))
{
my $samba = $conf->get('samba')->prop('status') || 'disabled';
my $sambaip = $conf->get('samba')->prop('SambaIP') || '';
my $sambapwd = $conf->get('samba')->prop('Password') || '';
if ($sambaip eq '' || $sambapwd eq '')
    {
        $samba = 'disabled';
    }
if ( ($samba eq 'enabled') && (-e "/usr/bin/samba-tool") )
{
system("/usr/bin/samba-tool", "user", "add", "$userName", "--random-password", "-H", "ldap://$sambaip", "--username=administrator", "--password=$sambapwd")
    and ( $x = 255, warn "Could not create (addc) user for $userName\n" );
system("/usr/bin/samba-tool", "user", "disable", "$userName", "-H", "ldap://$sambaip", "--username=administrator", "--password=$sambapwd")
    and ( $x = 255, warn "Could not lock (addc) password for $userName\n" );
}
}

exit ($x);
